version: '3.8'

services:
  surveillance-system:
    build: .
    container_name: ai-surveillance-system
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./models:/app/models
      - ./surveillance.db:/app/surveillance.db
      - ./vector_db:/app/vector_db
      - /dev/video0:/dev/video0  # For webcam access (Linux)
    devices:
      - /dev/video0:/dev/video0  # For webcam access (Linux)
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    privileged: true  # Required for camera access
    
  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: surveillance-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - surveillance-system
    restart: unless-stopped
    profiles:
      - production

volumes:
  surveillance_data:
    driver: local
